server:
    interface: 127.0.0.1
    port: 5353
    access-control: 127.0.0.0/8 allow
    do-ip6: no

    num-threads: 1
    prefetch: yes
    cache-min-ttl: 300
    cache-max-ttl: 86400
    hide-identity: yes
    hide-version: yes
    use-caps-for-id: yes

    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

forward-zone:
    name: "."
    forward-tls-upstream: yes

    # Quad9
    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 149.112.112.112@853#dns.quad9.net

    # Mullvad DNS
    forward-addr: 194.242.2.2@853#dns.mullvad.net
